adlibs = []
adlibs.append(("Insults", ["noun", "noun", "bodypart"], "The rankest {0} of villainous {1} that ever offended my {2}"))
adlibs.append(("Insults", ["ness", "verbs", "adjective", "nouns"], "The {0} of his face {1} {2} {3}."))
adlibs.append(("Insults", ["noun", "verbed", "noun"], "There’s no more {0} in thee than in a(n) {1} {2}."))
adlibs.append(("Insults", ["noun", "verbing"], "Thine {0}(noun) is not worth {1}."))
adlibs.append(("Insults", ["verbed", "adjective", "noun"], "Thou {0} and {1} {2}."))
adlibs.append(("Insults", ["adjective", "adjective", "noun"], "Thou {0}, perjur’d, false, {1} {2}!"))
adlibs.append(("Insults", ["noun", "verb"], "More of your {0} would {1} my brain."))
adlibs.append(("insults", ["insult0", "insult1", "insult2", "insult3"], "{0} {1} {2} {3}"))
adlibs.append(("insults", ["shinsult0", "shinsult1", "shinsult2", "shinsult3"], "{0} {1} {2} {3}"))

adlibs.append(("Proverbs", ["adjective", "verb"], "A woman's advice is no {0} thing, but he who won't {1} it is a fool."))
adlibs.append(("Proverbs", ["noun", "adjective"], "Absence makes the {0} grow {1} -er."))
adlibs.append(("Proverbs", ["noun", "verbs", "noun"], "A(n) {0} never {1} far from the {2}."))
adlibs.append(("Proverbs", ["noun", "adjective"], "Anyone can hold the {0} when the sea is {1} ."))
adlibs.append(("Proverbs", ["noun", "number", "noun"], "A(n) {0} in hand is worth {1} in the {2} ."))
adlibs.append(("Proverbs", ["adjective", "verbs"], "A(n) {0} mouth {1} no feet."))
adlibs.append(("Proverbs", ["adjective", "noun", "adjective", "nouns"], "A(n) {0} {1} believes anything, but a {2} {1} gives thought to his {3}."))
adlibs.append(("Proverbs", ["noun", "verbs"], "A {0} in time {1} nine." ))

adlibs.append(("Einstien", ["adjective", "adjective", "noun", "nouns"], "Any intelligent fool can make things {0} , more {1}, and more violent. It takes a touch of genius -- and a lot of {2} -- to move in the opposite {3}."))
adlibs.append(("Einstien", ["noun", "adjective"], "Reality is merely a(n) {0}, albeit a very {1} one."))
adlibs.append(("Einstien", ["nouns", "nouns"], "Great {0} have often encountered violent opposition from weak {1}."))
adlibs.append(("Einstien", ["noun", "occupation"], "Technological progress is like an {0} in the hands of a pathological {1}."))
adlibs.append(("Einstien", ["noun", "verb", "schoolsubject", "adjective"], "No, this {0} won`t work... How on earth are you ever going to {1} in terms of chemistry and {2} so important a biological phenomenon as {3} love?"))
adlibs.append(("Einstien", ["noun", "verbing", "bodypart", "occupation"], "The release of {0} power has changed everything except our way of {1}... the solution to this problem lies in the {2} of mankind. If only I had known, I should have become a/an {3}."))
