wlist={
"noun":["box", "turd", "laptop", "rabbit", "bag", "pilot", "canoe", "captain", "pirate", "hammer", "knob", "jockey", "nazi", "waffle", "goblin", "blossum", "biscuit", "clown", "socket", "monster", "hound", "dragon", "balloon"],
"nouns":["boxes", "turds", "laptops", "rabbits", "bags", "pilots", "canoes", "captains", "pirates", "hammers", "knobs", "jockies", "nazis", "waffles", "goblins", "blossums", "biscuits", "clowns", "sockets", "monsters", "hounds", "dragons", "balloons"],
"schoolsubject":["science", "math", "history", "economics", "English", "P.E.", "Spainish", "French", "Woodshop", "algebra", "geometry", "trigonometry", "band", "drama", "psychology", "physics", "calculus", "social studies", "civics", "literature"] ,
"bodypart":["arm", "leg", "head", "shoulder", "knee", "toe", "finger", "foot", "hand", "ankle", "eye", "nose", "mouth", "tongue", "elbow", "wrist"],
"bodyparts":["arms", "legs", "heads", "shoulders", "knees", "toes", "fingers", "feet", "hands", "ankles", "eyes", "noses", "mouths", "tongues", "elbows", "wrists"],

"adjective":["lazy", "stupid", "insecure", "idiotic", "slimy", "slutty", "smelly", "pompous", "communist", "dicknose", "pie-eating", "racist", "elitist", "white trash", "drug-loving", "butterface", "tone deaf", "ugly", "creepy"],
"ness":["lazyness", "sluttyness", "smellyness", "elitistness", "uglyness"] ,

"verb":["amuse", "analyze", "announce", "annoy", "answer", "apologize", "appeal", "appear", "applaud", "adopt", "affirm", "afford", "agree", "ail", "alert", "allege", "allow", "allude", "assure", "attach", "attack", "attempt", "attend", "attract", "auction", "avoid", "avow", "awake", "bathe", "battle", "bawl", "be", "beam", "bear", "beat", "become", "befriend", "beg", "begin", "behave", "believe", "bellow", "belong", "bend", "breathe", "breed", "bring", "broadcast", "broil", "bruise", "brush", "bubble", "build", "bump", "burn", "burnish", "bury", "buy", "buzz", "color", "comb", "come", "comfort", "command", "comment", "communicate", "compare", "compete", "complain", "complete", "concede", "concentrate", "concern", "conclude", "concur", "confess", "dial", "dictate", "die", "dig", "digress", "direct", "disclose", "dislike", "dive", "divide", "divorce", "divulge", "heap", "hear", "heat", "help", "hide", "highlight", "hijack"],
"verbs":["amuses", "analyzes", "announces", "annoys", "answers", "apologizes", "appeals", "appears", "applauds", "adopts", "affirms", "affords", "agrees", "ails", "alerts", "alleges", "allows", "alludes", "assures", "attaches", "attacks", "attempts", "attends", "attracts", "auctions", "avoids", "avows", "awakes", "bathes", "battles", "bawls", "is", "beams", "bears", "beats", "becomes", "befriends", "begs", "begins", "behaves", "believes", "bellows", "belongs", "bends", "breathes", "breeds", "brings", "broadcasts", "broils", "bruises", "brushes", "bubbles", "builds", "bumps", "burns", "burnishes", "buries", "buys", "buzzes", "colors", "combs", "comes", "comforts", "commands", "comments", "communicates", "compares", "competes", "complains", "completes", "concedes", "concentrates", "concerns", "concludes", "concurs", "confesses", "dials", "dictates", "dies", "digs", "digresses", "directs", "discloses", "dislikes", "dives", "divides", "divorces", "divulges", "heaps", "hears", "heats", "helps", "hides", "highlights", "hijacks"],
"verbed":["amused", "analyzed", "announced", "annoyed", "answered", "apologized", "appealed", "appeared", "applauded", "adopted", "affirmed", "afforded", "agreeed", "ailed", "alerted", "alleged", "allowed", "alluded", "assured", "attached", "attacked", "attempted", "attended", "attracted", "auctioned", "avoided", "avowed", "awakend", "bathed", "battled", "bawled", "was", "beamed", "bore", "beat", "became", "befriended", "begged", "began", "behaved", "believed", "bellowed", "belonged", "bended", "breathed", "bred", "brang", "broadcasted", "broiled", "bruised", "brushed", "bubbled", "builded", "bumped", "burned", "burnished", "buried", "bought", "buzzed", "colored", "combed", "came", "comforted", "commanded", "commented", "communicated", "compared", "competed", "complained", "completed", "conceded", "concentrated", "concerned", "concluded", "concured", "confessed", "dialed", "dictated", "died", "dug", "digressed", "directed", "disclosed", "disliked", "dove", "divided", "divorced", "divulged", "heaped", "heard", "heated", "helped", "hid", "highlighted", "hijacked"],
"verbing":["amusing", "analyzing", "announcing", "annoying", "answering", "apologizing", "appealing", "appearing", "applauding", "adopting", "affirming", "affording", "agreeing", "ailing", "alerting", "alleging", "allowing", "alluding", "assuring", "attaching", "attacking", "attempting", "attending", "attracting", "auctioning", "avoiding", "avowing", "awaking", "bathing", "battling", "bawling", "being", "beaming", "bearing", "beating", "becoming", "befriending", "begging", "begining", "behaving", "believing", "bellowing", "belonging", "bending", "breathing", "breeding", "bringing", "broadcasting", "broiling", "bruising", "brushing", "bubbling", "building", "bumping", "burning", "burnishing", "burying", "buying", "buzzing", "coloring", "combing", "coming", "comforting", "commanding", "commenting", "communicateing", "compareing", "competeing", "complaining", "completing", "conceding", "concentrating", "concerning", "concluding", "concuring", "confessing", "dialing", "dictating", "dieing", "digging", "digressing", "directing", "disclosing", "disliking", "diving", "dividing", "divorcing", "divulging", "heaping", "hearing", "heating", "helping", "hiding", "highlighting", "hijacking"],

"occupation":["mecanic", "tech support", "engineer", "doctor", "chef", "tailor", "teacher", "pastor", "prostitute", "therapist", "musician", "security guard", "conductor", "farmer", "cowbow", "miner"],


"insult0":['Your face looks like', 'You\'re', 'Your mom is'],
"insult1":["a Lazy", "a Stupid", "an Insecure", "an Idiotic", "a Slimy", "a Slutty", "a Smelly", "a Pompous", "a Communist", "a Dicknose", "a Pie-eating", "a Racist", "an Elitist", "a White Trash", "a Drug-Loving", "a Butterface", "a Tone Deaf", "an Ugly", "a Creepy"],
"insult2":["Douche", "Ass", "Turd", "Rectum", "Butt", "Cock", "Shit", "Crotch", "Bitch", "Prick", "Slut", "Taint", "Fuck", "Dick", "Boner", "Shart", "Nut", "Sphincter" ],
"insult3":["Pilot", "Canoe", "Captain", "Pirate", "Hammer", "Knob", "Box", "Jockey", "Nazi", "Waffle", "Goblin", "Blossum", "Biscuit", "Clown", "Socket", "Monster", "Hound", "Dragon", "Balloon"],

"shinsult0":["Thou art a(n)"],
"shinsult1":["artless", "bawdy", "beslubbering", "bootless", "churlish", "cockered", "clouted", "craven", "currish", "dankish", "dissembling", "droning", "errant", "fawning", "fobbing", "froward", "frothy", "gleeking", "goatish", "gorebllied", "impertinent", "infectious", "jarring", "loggerhead", "lumpish", "mammering", "mangled", "mewling", "paunchy", "pribbling", "puking", "puny", "qualling", "rank", "reeky", "rogueish", "ruttish", "saucy", "spleeny", "surly", "tottering", "unmuzzeld", "vain", "venomed", "villainous", "warped", "wayward", "weedy", "yeasty"],
"shinsult2":["base-court", "bat-fowling", "beef-witted", "beetle-headed", "boil-brained", "clapper-clawed", "clay-brained", "common-kissing", "crook-pated", "dismal-dreaming", "dizzey-eyed", "doghearted", "dread-bolted", "earth-vexing", "elf-skinned", "fat-kideyed", "fen-sucked", "flap-mouthed", "fly-bitten", "folly-fallen", "fool-born", "full-gorged", "guts-griping", "half-faced", "hasty-witted", "hedge-born", "hell-hated", "idle-headed", "ill-breeding", "ill-nurtured", "knotty-pated", "milk-livered", "motley-minded", "onion-eyed", "plume-plucked", "pottle-deep", "pox-marked", "reeling-ripe", "rough-hewn", "rude-growing", "rump-fed", "shard-borne", "sheep-biting", "spur-galled", "swag-bellied", "tardy-gaited", "tickle-brained", "toar-spotted", "unchin-snouted", "weather-bitten"],
"shinsult3":["apple-john", "baggage", "barnacle", "bladder", "boar-pig", "bugbear", "bum-bailey", "canker-blossom", "clack-dish", "clotpole", "coxcomb", "codpiece", "death-token", "dewberry", "flap-dragon", "flax-wench", "flirt-gill", "foot-licker", "fustilarian", "giglet", "gudgeon", "haggard", "harpy", "hedge-pie", "horn-beast", "hugger-mugger", "joithead", "lewdster", "lout", "maggot-pie", "malt-worm", "mammet", "measle", "minnow", "miscreant", "moldwarp", "mumble-news", "nut-hook", "pigeon-egg", "pignut", "puttock", "pumpion", "ratsbane", "scut", "skainsmate", "strumpet", "varlot", "vassal", "whey-face", "wagtail"]
}
